server:
  port: 8080

spring:
  #Configuracion provicional debido a que no se configura aun el microservicio-config
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8090
          predicates:
            - Path=/api/student/**
        - id: courses
          uri: http://localhost:9090
          predicates:
            - Path=/api/course/**
